// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/zrma/1d1go/cmd/micro/booking/srv/profile/proto/profile.proto

package profile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	HotelIds             []string `protobuf:"bytes,1,rep,name=hotelIds,proto3" json:"hotelIds,omitempty"`
	Locale               string   `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b639af101e388b0, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetHotelIds() []string {
	if m != nil {
		return m.HotelIds
	}
	return nil
}

func (m *Request) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

type Result struct {
	Hotels               []*Hotel `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b639af101e388b0, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetHotels() []*Hotel {
	if m != nil {
		return m.Hotels
	}
	return nil
}

type Hotel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Address              *Address `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Images               []*Image `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hotel) Reset()         { *m = Hotel{} }
func (m *Hotel) String() string { return proto.CompactTextString(m) }
func (*Hotel) ProtoMessage()    {}
func (*Hotel) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b639af101e388b0, []int{2}
}

func (m *Hotel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hotel.Unmarshal(m, b)
}
func (m *Hotel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hotel.Marshal(b, m, deterministic)
}
func (m *Hotel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hotel.Merge(m, src)
}
func (m *Hotel) XXX_Size() int {
	return xxx_messageInfo_Hotel.Size(m)
}
func (m *Hotel) XXX_DiscardUnknown() {
	xxx_messageInfo_Hotel.DiscardUnknown(m)
}

var xxx_messageInfo_Hotel proto.InternalMessageInfo

func (m *Hotel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Hotel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hotel) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Hotel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Hotel) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Hotel) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type Address struct {
	StreetNumber         string   `protobuf:"bytes,1,opt,name=streetNumber,proto3" json:"streetNumber,omitempty"`
	StreetName           string   `protobuf:"bytes,2,opt,name=streetName,proto3" json:"streetName,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode           string   `protobuf:"bytes,6,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b639af101e388b0, []int{3}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetStreetNumber() string {
	if m != nil {
		return m.StreetNumber
	}
	return ""
}

func (m *Address) GetStreetName() string {
	if m != nil {
		return m.StreetName
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

type Image struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Default              bool     `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b639af101e388b0, []int{4}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Image) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "profile.Request")
	proto.RegisterType((*Result)(nil), "profile.Result")
	proto.RegisterType((*Hotel)(nil), "profile.Hotel")
	proto.RegisterType((*Address)(nil), "profile.Address")
	proto.RegisterType((*Image)(nil), "profile.Image")
}

func init() {
	proto.RegisterFile("github.com/zrma/1d1go/cmd/micro/booking/srv/profile/proto/profile.proto", fileDescriptor_4b639af101e388b0)
}

var fileDescriptor_4b639af101e388b0 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x86, 0xb5, 0x49, 0xb3, 0xdb, 0x4c, 0x50, 0xa9, 0x46, 0x08, 0x59, 0x3d, 0xa0, 0x68, 0x0f,
	0x28, 0xe2, 0x90, 0x6d, 0xd3, 0x23, 0xe2, 0x80, 0x90, 0x80, 0x5e, 0x10, 0xf2, 0x1b, 0x38, 0xf6,
	0x34, 0xb1, 0xf0, 0xae, 0x83, 0xed, 0x45, 0x2a, 0x6f, 0xc5, 0x33, 0xf0, 0x62, 0xc8, 0x5e, 0x6f,
	0x12, 0x7a, 0xf2, 0xfc, 0xdf, 0x8c, 0x3d, 0xf3, 0x5b, 0x03, 0x9f, 0x77, 0x3a, 0xec, 0xfb, 0xed,
	0x5a, 0xda, 0xb6, 0xf9, 0xed, 0x5a, 0xd1, 0xdc, 0xa9, 0x3b, 0xd9, 0xc8, 0x56, 0x35, 0xad, 0x96,
	0xce, 0x36, 0x5b, 0x6b, 0x7f, 0xe8, 0x6e, 0xd7, 0x78, 0xf7, 0xab, 0x39, 0x38, 0xfb, 0xa8, 0x0d,
	0xc5, 0x33, 0xd8, 0x51, 0xad, 0x93, 0xc2, 0x2a, 0xcb, 0xfa, 0x03, 0x54, 0x9c, 0x7e, 0xf6, 0xe4,
	0x03, 0xde, 0xc0, 0xe5, 0xde, 0x06, 0x32, 0x0f, 0xca, 0xb3, 0x62, 0x39, 0x5d, 0xcd, 0xf9, 0x51,
	0xe3, 0x6b, 0x28, 0x8d, 0x95, 0xc2, 0x10, 0x9b, 0x2c, 0x8b, 0xd5, 0x9c, 0x67, 0x55, 0xdf, 0x42,
	0xc9, 0xc9, 0xf7, 0x26, 0xe0, 0x5b, 0x28, 0x53, 0xf5, 0x70, 0x77, 0xb1, 0xb9, 0x5a, 0x8f, 0x1d,
	0xbf, 0x46, 0xcc, 0x73, 0xb6, 0xfe, 0x5b, 0xc0, 0x2c, 0x11, 0xbc, 0x82, 0x89, 0x56, 0xac, 0x48,
	0xef, 0x4d, 0xb4, 0x42, 0x84, 0x8b, 0x4e, 0xb4, 0x63, 0x87, 0x14, 0xe3, 0x12, 0x16, 0x87, 0xbd,
	0xed, 0xe8, 0x5b, 0xdf, 0x6e, 0xc9, 0xb1, 0x69, 0x4a, 0x9d, 0xa3, 0x58, 0xa1, 0xc8, 0x4b, 0xa7,
	0x0f, 0x41, 0xdb, 0x8e, 0x5d, 0x0c, 0x15, 0x67, 0x08, 0xdf, 0x41, 0x25, 0x94, 0x72, 0xe4, 0x3d,
	0x9b, 0x2d, 0x8b, 0xd5, 0x62, 0x73, 0x7d, 0x1c, 0xed, 0xe3, 0xc0, 0xf9, 0x58, 0x10, 0x5d, 0xe8,
	0x56, 0xec, 0xc8, 0xb3, 0xf2, 0x99, 0x8b, 0x87, 0x88, 0x79, 0xce, 0xd6, 0x7f, 0x0a, 0xa8, 0xf2,
	0x65, 0xac, 0xe1, 0x85, 0x0f, 0x8e, 0x28, 0xe4, 0x21, 0x07, 0x47, 0xff, 0x31, 0x7c, 0x03, 0x90,
	0xf5, 0xc9, 0xe1, 0x19, 0x89, 0xde, 0xa5, 0x0e, 0x4f, 0xd9, 0x60, 0x8a, 0xf1, 0x15, 0xcc, 0x7c,
	0x10, 0x81, 0xb2, 0xa7, 0x41, 0x20, 0x83, 0x4a, 0xda, 0xbe, 0x0b, 0xee, 0x29, 0xb9, 0x99, 0xf3,
	0x51, 0xc6, 0x1e, 0x07, 0xeb, 0x83, 0x30, 0x9f, 0xac, 0x22, 0x56, 0x0e, 0x3d, 0x4e, 0xa4, 0xbe,
	0x87, 0x59, 0x32, 0x81, 0xd7, 0x30, 0xed, 0x9d, 0xc9, 0x73, 0xc6, 0x30, 0x3e, 0xaa, 0xe8, 0x51,
	0xf4, 0x26, 0xa4, 0xd9, 0x2e, 0xf9, 0x28, 0x37, 0xef, 0xa1, 0xfa, 0x3e, 0xfc, 0x00, 0xde, 0xc2,
	0xe2, 0x0b, 0x85, 0xac, 0x3c, 0x9e, 0x7e, 0x31, 0x2f, 0xd0, 0xcd, 0xcb, 0x33, 0x12, 0x77, 0x62,
	0x5b, 0xa6, 0x65, 0xbb, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x73, 0x73, 0xf9, 0x7e, 0xb6, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileClient is the client API for Profile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileClient interface {
	GetProfiles(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
}

type profileClient struct {
	cc *grpc.ClientConn
}

func NewProfileClient(cc *grpc.ClientConn) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) GetProfiles(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/profile.Profile/GetProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServer is the server API for Profile service.
type ProfileServer interface {
	GetProfiles(context.Context, *Request) (*Result, error)
}

// UnimplementedProfileServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServer struct {
}

func (*UnimplementedProfileServer) GetProfiles(ctx context.Context, req *Request) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfiles not implemented")
}

func RegisterProfileServer(s *grpc.Server, srv ProfileServer) {
	s.RegisterService(&_Profile_serviceDesc, srv)
}

func _Profile_GetProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.Profile/GetProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetProfiles(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profile.Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfiles",
			Handler:    _Profile_GetProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/zrma/1d1go/cmd/micro/booking/srv/profile/proto/profile.proto",
}
