// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/hotel/proto/hotel.proto

package hotel

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	proto1 "srv/profile/proto"
	proto2 "srv/rate/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	InDate               string   `protobuf:"bytes,1,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate              string   `protobuf:"bytes,2,opt,name=outDate,proto3" json:"outDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_79a2533c01ad0874, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetInDate() string {
	if m != nil {
		return m.InDate
	}
	return ""
}

func (m *Request) GetOutDate() string {
	if m != nil {
		return m.OutDate
	}
	return ""
}

type Response struct {
	Hotels               []*proto1.Hotel    `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	RatePlans            []*proto2.RatePlan `protobuf:"bytes,2,rep,name=ratePlans,proto3" json:"ratePlans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_79a2533c01ad0874, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHotels() []*proto1.Hotel {
	if m != nil {
		return m.Hotels
	}
	return nil
}

func (m *Response) GetRatePlans() []*proto2.RatePlan {
	if m != nil {
		return m.RatePlans
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "hotel.Request")
	proto.RegisterType((*Response)(nil), "hotel.Response")
}

func init() { proto.RegisterFile("api/hotel/proto/hotel.proto", fileDescriptor_79a2533c01ad0874) }

var fileDescriptor_79a2533c01ad0874 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xc1, 0xeb, 0x82, 0x30,
	0x14, 0xc7, 0x7f, 0xfa, 0x43, 0xcd, 0x17, 0x18, 0xec, 0x10, 0xcb, 0x0e, 0x89, 0x87, 0x90, 0x08,
	0x05, 0x3d, 0x76, 0xed, 0xd0, 0x31, 0xf6, 0x17, 0xb4, 0x60, 0x91, 0x20, 0xce, 0xdc, 0xec, 0xef,
	0x8f, 0xbd, 0xcd, 0xba, 0xbd, 0xef, 0xfb, 0x7c, 0xc7, 0x3e, 0x1b, 0x6c, 0xf9, 0xd0, 0x56, 0x4f,
	0xa9, 0x45, 0x57, 0x0d, 0xa3, 0xd4, 0xd2, 0xce, 0x25, 0xce, 0x24, 0xc0, 0x90, 0xee, 0xd4, 0xf8,
	0x36, 0xf4, 0xd1, 0x76, 0xc2, 0xb5, 0x5c, 0xb2, 0xbd, 0x74, 0x63, 0x0a, 0x23, 0xd7, 0x33, 0x35,
	0xa3, 0x45, 0xf9, 0x09, 0x22, 0x26, 0x5e, 0x93, 0x50, 0x9a, 0xac, 0x21, 0x6c, 0xfb, 0x33, 0xd7,
	0x82, 0x7a, 0x99, 0x57, 0xc4, 0xcc, 0x25, 0x42, 0x21, 0x92, 0x93, 0x46, 0xe0, 0x23, 0x98, 0x63,
	0x7e, 0x83, 0x05, 0x13, 0x6a, 0x90, 0xbd, 0x12, 0x64, 0x0f, 0x21, 0xda, 0x28, 0xea, 0x65, 0xff,
	0xc5, 0xb2, 0x4e, 0xca, 0xd9, 0xe1, 0x62, 0xd6, 0xcc, 0x51, 0x72, 0x84, 0xd8, 0x5c, 0x7f, 0xed,
	0x78, 0xaf, 0xa8, 0xef, 0xaa, 0x28, 0xc4, 0xdc, 0x9a, 0xfd, 0x0a, 0x75, 0x03, 0x01, 0x1e, 0x27,
	0x07, 0x08, 0x0c, 0x57, 0x24, 0x29, 0xed, 0x0f, 0x38, 0xeb, 0x74, 0xf5, 0xcd, 0x56, 0x24, 0xff,
	0xbb, 0x87, 0xf8, 0xb4, 0xe6, 0x13, 0x00, 0x00, 0xff, 0xff, 0xae, 0x5a, 0x44, 0xdb, 0x3c, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HotelClient is the client API for Hotel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HotelClient interface {
	Rates(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type hotelClient struct {
	cc *grpc.ClientConn
}

func NewHotelClient(cc *grpc.ClientConn) HotelClient {
	return &hotelClient{cc}
}

func (c *hotelClient) Rates(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/hotel.Hotel/Rates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotelServer is the server API for Hotel service.
type HotelServer interface {
	Rates(context.Context, *Request) (*Response, error)
}

// UnimplementedHotelServer can be embedded to have forward compatible implementations.
type UnimplementedHotelServer struct {
}

func (*UnimplementedHotelServer) Rates(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rates not implemented")
}

func RegisterHotelServer(s *grpc.Server, srv HotelServer) {
	s.RegisterService(&_Hotel_serviceDesc, srv)
}

func _Hotel_Rates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServer).Rates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hotel.Hotel/Rates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServer).Rates(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hotel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hotel.Hotel",
	HandlerType: (*HotelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rates",
			Handler:    _Hotel_Rates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/hotel/proto/hotel.proto",
}
