// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/zrma/1d1go/cmd/micro/booking/srv/geo/proto/geo.proto

package geo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Geo service

type GeoService interface {
	// Finds the hotels contained nearby the current lat/lon.
	Nearby(ctx context.Context, in *Request, opts ...client.CallOption) (*Result, error)
}

type geoService struct {
	c    client.Client
	name string
}

func NewGeoService(name string, c client.Client) GeoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "geo"
	}
	return &geoService{
		c:    c,
		name: name,
	}
}

func (c *geoService) Nearby(ctx context.Context, in *Request, opts ...client.CallOption) (*Result, error) {
	req := c.c.NewRequest(c.name, "Geo.Nearby", in)
	out := new(Result)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Geo service

type GeoHandler interface {
	// Finds the hotels contained nearby the current lat/lon.
	Nearby(context.Context, *Request, *Result) error
}

func RegisterGeoHandler(s server.Server, hdlr GeoHandler, opts ...server.HandlerOption) error {
	type geo interface {
		Nearby(ctx context.Context, in *Request, out *Result) error
	}
	type Geo struct {
		geo
	}
	h := &geoHandler{hdlr}
	return s.Handle(s.NewHandler(&Geo{h}, opts...))
}

type geoHandler struct {
	GeoHandler
}

func (h *geoHandler) Nearby(ctx context.Context, in *Request, out *Result) error {
	return h.GeoHandler.Nearby(ctx, in, out)
}
