// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/zrma/1d1c/cmd/micro/booking/srv/geo/proto/geo.proto

package geo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The latitude and longitude of the current location.
type Request struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_571dd1605a16b3e5, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Request) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type Result struct {
	HotelIds             []string `protobuf:"bytes,1,rep,name=hotelIds,proto3" json:"hotelIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_571dd1605a16b3e5, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetHotelIds() []string {
	if m != nil {
		return m.HotelIds
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "geo.Request")
	proto.RegisterType((*Result)(nil), "geo.Result")
}

func init() {
	proto.RegisterFile("github.com/zrma/1d1c/cmd/micro/booking/srv/geo/proto/geo.proto", fileDescriptor_571dd1605a16b3e5)
}

var fileDescriptor_571dd1605a16b3e5 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x31, 0x6f, 0x83, 0x30,
	0x10, 0x46, 0x05, 0x96, 0x68, 0xeb, 0x76, 0xa8, 0x3c, 0x21, 0x26, 0x44, 0x3b, 0xa0, 0x4a, 0xe5,
	0x44, 0xbb, 0x67, 0x8d, 0xb2, 0x64, 0xf0, 0x3f, 0xc0, 0xe6, 0x64, 0x50, 0x30, 0x97, 0xd8, 0x26,
	0x52, 0xf2, 0xeb, 0x23, 0x23, 0x94, 0xed, 0x7d, 0x6f, 0xb8, 0x77, 0x7c, 0x67, 0xc6, 0x30, 0x2c,
	0xaa, 0xd1, 0x64, 0xe1, 0xee, 0x6c, 0x07, 0x6d, 0xdf, 0x6a, 0xd0, 0xb6, 0x07, 0x3b, 0x6a, 0x47,
	0xa0, 0x88, 0x4e, 0xe3, 0x6c, 0xc0, 0xbb, 0x2b, 0x18, 0x24, 0x38, 0x3b, 0x0a, 0x14, 0xa9, 0x59,
	0x49, 0x30, 0x83, 0x54, 0xfd, 0xf2, 0x17, 0x89, 0x97, 0x05, 0x7d, 0x10, 0x9f, 0x9c, 0x4d, 0x5d,
	0xc8, 0x93, 0x32, 0xa9, 0x53, 0x19, 0x71, 0x35, 0x34, 0xe7, 0xe9, 0x66, 0x68, 0xae, 0xbe, 0x79,
	0x26, 0xd1, 0x2f, 0x53, 0x10, 0x05, 0x7f, 0x1d, 0x28, 0xe0, 0x74, 0xe8, 0x7d, 0x9e, 0x94, 0xac,
	0x7e, 0x93, 0xcf, 0xfd, 0xf7, 0xc3, 0xd9, 0x1e, 0x49, 0x7c, 0xf1, 0xec, 0x88, 0x9d, 0x53, 0x37,
	0xf1, 0xd1, 0xc4, 0xec, 0x16, 0x2a, 0xde, 0xb7, 0x15, 0xef, 0xa8, 0x6c, 0x7d, 0xe6, 0xff, 0x11,
	0x00, 0x00, 0xff, 0xff, 0x75, 0xc3, 0x42, 0x28, 0xce, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GeoClient is the client API for Geo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeoClient interface {
	// Finds the hotels contained nearby the current lat/lon.
	Nearby(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
}

type geoClient struct {
	cc *grpc.ClientConn
}

func NewGeoClient(cc *grpc.ClientConn) GeoClient {
	return &geoClient{cc}
}

func (c *geoClient) Nearby(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/geo.Geo/Nearby", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoServer is the server API for Geo service.
type GeoServer interface {
	// Finds the hotels contained nearby the current lat/lon.
	Nearby(context.Context, *Request) (*Result, error)
}

// UnimplementedGeoServer can be embedded to have forward compatible implementations.
type UnimplementedGeoServer struct {
}

func (*UnimplementedGeoServer) Nearby(ctx context.Context, req *Request) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Nearby not implemented")
}

func RegisterGeoServer(s *grpc.Server, srv GeoServer) {
	s.RegisterService(&_Geo_serviceDesc, srv)
}

func _Geo_Nearby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoServer).Nearby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geo.Geo/Nearby",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoServer).Nearby(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Geo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "geo.Geo",
	HandlerType: (*GeoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Nearby",
			Handler:    _Geo_Nearby_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/zrma/1d1c/cmd/micro/booking/srv/geo/proto/geo.proto",
}
