// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/zrma/1d1c/cmd/micro/booking/srv/rate/proto/rate.proto

package rate

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	HotelIds             []string `protobuf:"bytes,1,rep,name=hotelIds,proto3" json:"hotelIds,omitempty"`
	InDate               string   `protobuf:"bytes,2,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate              string   `protobuf:"bytes,3,opt,name=outDate,proto3" json:"outDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_74899f80fdd294a3, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetHotelIds() []string {
	if m != nil {
		return m.HotelIds
	}
	return nil
}

func (m *Request) GetInDate() string {
	if m != nil {
		return m.InDate
	}
	return ""
}

func (m *Request) GetOutDate() string {
	if m != nil {
		return m.OutDate
	}
	return ""
}

type Result struct {
	RatePlans            []*RatePlan `protobuf:"bytes,1,rep,name=ratePlans,proto3" json:"ratePlans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_74899f80fdd294a3, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetRatePlans() []*RatePlan {
	if m != nil {
		return m.RatePlans
	}
	return nil
}

type RatePlan struct {
	HotelId              string    `protobuf:"bytes,1,opt,name=hotelId,proto3" json:"hotelId,omitempty"`
	Code                 string    `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	InDate               string    `protobuf:"bytes,3,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate              string    `protobuf:"bytes,4,opt,name=outDate,proto3" json:"outDate,omitempty"`
	RoomType             *RoomType `protobuf:"bytes,5,opt,name=roomType,proto3" json:"roomType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RatePlan) Reset()         { *m = RatePlan{} }
func (m *RatePlan) String() string { return proto.CompactTextString(m) }
func (*RatePlan) ProtoMessage()    {}
func (*RatePlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_74899f80fdd294a3, []int{2}
}

func (m *RatePlan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatePlan.Unmarshal(m, b)
}
func (m *RatePlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatePlan.Marshal(b, m, deterministic)
}
func (m *RatePlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatePlan.Merge(m, src)
}
func (m *RatePlan) XXX_Size() int {
	return xxx_messageInfo_RatePlan.Size(m)
}
func (m *RatePlan) XXX_DiscardUnknown() {
	xxx_messageInfo_RatePlan.DiscardUnknown(m)
}

var xxx_messageInfo_RatePlan proto.InternalMessageInfo

func (m *RatePlan) GetHotelId() string {
	if m != nil {
		return m.HotelId
	}
	return ""
}

func (m *RatePlan) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RatePlan) GetInDate() string {
	if m != nil {
		return m.InDate
	}
	return ""
}

func (m *RatePlan) GetOutDate() string {
	if m != nil {
		return m.OutDate
	}
	return ""
}

func (m *RatePlan) GetRoomType() *RoomType {
	if m != nil {
		return m.RoomType
	}
	return nil
}

type RoomType struct {
	BookableRate         float64  `protobuf:"fixed64,1,opt,name=bookableRate,proto3" json:"bookableRate,omitempty"`
	TotalRate            float64  `protobuf:"fixed64,2,opt,name=totalRate,proto3" json:"totalRate,omitempty"`
	TotalRateInclusive   float64  `protobuf:"fixed64,3,opt,name=totalRateInclusive,proto3" json:"totalRateInclusive,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Currency             string   `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	RoomDescription      string   `protobuf:"bytes,6,opt,name=roomDescription,proto3" json:"roomDescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomType) Reset()         { *m = RoomType{} }
func (m *RoomType) String() string { return proto.CompactTextString(m) }
func (*RoomType) ProtoMessage()    {}
func (*RoomType) Descriptor() ([]byte, []int) {
	return fileDescriptor_74899f80fdd294a3, []int{3}
}

func (m *RoomType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomType.Unmarshal(m, b)
}
func (m *RoomType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomType.Marshal(b, m, deterministic)
}
func (m *RoomType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomType.Merge(m, src)
}
func (m *RoomType) XXX_Size() int {
	return xxx_messageInfo_RoomType.Size(m)
}
func (m *RoomType) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomType.DiscardUnknown(m)
}

var xxx_messageInfo_RoomType proto.InternalMessageInfo

func (m *RoomType) GetBookableRate() float64 {
	if m != nil {
		return m.BookableRate
	}
	return 0
}

func (m *RoomType) GetTotalRate() float64 {
	if m != nil {
		return m.TotalRate
	}
	return 0
}

func (m *RoomType) GetTotalRateInclusive() float64 {
	if m != nil {
		return m.TotalRateInclusive
	}
	return 0
}

func (m *RoomType) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RoomType) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *RoomType) GetRoomDescription() string {
	if m != nil {
		return m.RoomDescription
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "rate.Request")
	proto.RegisterType((*Result)(nil), "rate.Result")
	proto.RegisterType((*RatePlan)(nil), "rate.RatePlan")
	proto.RegisterType((*RoomType)(nil), "rate.RoomType")
}

func init() {
	proto.RegisterFile("github.com/zrma/1d1c/cmd/micro/booking/srv/rate/proto/rate.proto", fileDescriptor_74899f80fdd294a3)
}

var fileDescriptor_74899f80fdd294a3 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x6a, 0xe3, 0x30,
	0x10, 0xc7, 0xd1, 0xc6, 0xeb, 0xd8, 0xb3, 0xd9, 0x5d, 0x98, 0x43, 0x31, 0xa1, 0x87, 0xe0, 0x4b,
	0x43, 0x29, 0x16, 0x49, 0xa1, 0xe7, 0x1e, 0x02, 0x25, 0xb7, 0x22, 0x0a, 0x3d, 0xdb, 0xb2, 0x48,
	0x4c, 0x6d, 0x2b, 0x95, 0xe5, 0x40, 0xfa, 0x20, 0x7d, 0xb4, 0x3e, 0x4f, 0x91, 0x2c, 0x3b, 0x49,
	0x69, 0x6f, 0xff, 0x0f, 0x31, 0xfe, 0x69, 0x2c, 0xb8, 0xdf, 0x14, 0x7a, 0xdb, 0x66, 0x09, 0x97,
	0x15, 0x7d, 0x53, 0x55, 0x4a, 0x17, 0xf9, 0x82, 0x53, 0x5e, 0xe5, 0xb4, 0x2a, 0xb8, 0x92, 0x34,
	0x93, 0xf2, 0xa5, 0xa8, 0x37, 0xb4, 0x51, 0x7b, 0xaa, 0x52, 0x2d, 0xe8, 0x4e, 0x49, 0x2d, 0xad,
	0x4c, 0xac, 0x44, 0xcf, 0xe8, 0xf8, 0x19, 0xc6, 0x4c, 0xbc, 0xb6, 0xa2, 0xd1, 0x38, 0x85, 0x60,
	0x2b, 0xb5, 0x28, 0xd7, 0x79, 0x13, 0x91, 0xd9, 0x68, 0x1e, 0xb2, 0xc1, 0xe3, 0x05, 0xf8, 0x45,
	0xbd, 0x4a, 0xb5, 0x88, 0x7e, 0xcd, 0xc8, 0x3c, 0x64, 0xce, 0x61, 0x04, 0x63, 0xd9, 0x6a, 0x5b,
	0x8c, 0x6c, 0xd1, 0xdb, 0xf8, 0x0e, 0x7c, 0x26, 0x9a, 0xb6, 0xd4, 0x78, 0x03, 0xa1, 0xf9, 0xd4,
	0x63, 0x99, 0xd6, 0xdd, 0xe0, 0x3f, 0xcb, 0x7f, 0x89, 0x05, 0x61, 0x2e, 0x66, 0xc7, 0x03, 0xf1,
	0x3b, 0x81, 0xa0, 0xcf, 0xcd, 0x78, 0x87, 0x10, 0x91, 0x6e, 0xbc, 0xb3, 0x88, 0xe0, 0x71, 0x99,
	0xf7, 0x38, 0x56, 0x9f, 0x40, 0x8e, 0x7e, 0x82, 0xf4, 0xce, 0x20, 0xf1, 0x1a, 0x02, 0x25, 0x65,
	0xf5, 0x74, 0xd8, 0x89, 0xe8, 0xf7, 0x8c, 0x9c, 0x90, 0xb9, 0x94, 0x0d, 0x7d, 0xfc, 0x61, 0xc0,
	0x9c, 0xc1, 0x18, 0x26, 0x66, 0xc3, 0x69, 0x56, 0x0a, 0x03, 0x6b, 0xe9, 0x08, 0x3b, 0xcb, 0xf0,
	0x12, 0x42, 0x2d, 0x75, 0x5a, 0xb2, 0x7e, 0x6d, 0x84, 0x1d, 0x03, 0x4c, 0x00, 0x07, 0xb3, 0xae,
	0x79, 0xd9, 0x36, 0xc5, 0xbe, 0x03, 0x27, 0xec, 0x9b, 0x66, 0xb8, 0xb0, 0x77, 0x72, 0xe1, 0x29,
	0x04, 0xbc, 0x55, 0x4a, 0xd4, 0xfc, 0x60, 0xf1, 0x43, 0x36, 0x78, 0x9c, 0xc3, 0x7f, 0x83, 0xbe,
	0x12, 0x0d, 0x57, 0xc5, 0x4e, 0x17, 0xb2, 0x8e, 0x7c, 0x7b, 0xe4, 0x6b, 0xbc, 0xa4, 0xe0, 0x59,
	0xa2, 0x2b, 0x08, 0x1e, 0x84, 0x36, 0xb2, 0xc1, 0xbf, 0x6e, 0x0d, 0xdd, 0xd3, 0x98, 0x4e, 0x7a,
	0x6b, 0x7e, 0x68, 0xe6, 0xdb, 0x07, 0x74, 0xfb, 0x19, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xd9, 0x7d,
	0x18, 0x84, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RateClient is the client API for Rate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RateClient interface {
	// GetRates returns rate codes for hotels for a given date range
	GetRates(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
}

type rateClient struct {
	cc *grpc.ClientConn
}

func NewRateClient(cc *grpc.ClientConn) RateClient {
	return &rateClient{cc}
}

func (c *rateClient) GetRates(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/rate.Rate/GetRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateServer is the server API for Rate service.
type RateServer interface {
	// GetRates returns rate codes for hotels for a given date range
	GetRates(context.Context, *Request) (*Result, error)
}

// UnimplementedRateServer can be embedded to have forward compatible implementations.
type UnimplementedRateServer struct {
}

func (*UnimplementedRateServer) GetRates(ctx context.Context, req *Request) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRates not implemented")
}

func RegisterRateServer(s *grpc.Server, srv RateServer) {
	s.RegisterService(&_Rate_serviceDesc, srv)
}

func _Rate_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateServer).GetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rate.Rate/GetRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateServer).GetRates(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rate.Rate",
	HandlerType: (*RateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRates",
			Handler:    _Rate_GetRates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/zrma/1d1c/cmd/micro/booking/srv/rate/proto/rate.proto",
}
