// Code generated by entc, DO NOT EDIT.

package car

const (
	// Label holds the string label denoting the car type in the database.
	Label = "car"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModel holds the string denoting the model vertex property in the database.
	FieldModel = "model"
	// FieldRegisteredAt holds the string denoting the registered_at vertex property in the database.
	FieldRegisteredAt = "registered_at"

	// Table holds the table name of the car in the database.
	Table = "cars"
)

// Columns holds all SQL columns are car fields.
var Columns = []string{
	FieldID,
	FieldModel,
	FieldRegisteredAt,
}
