// Code generated by entc, DO NOT EDIT.

package group

import (
	"github.com/zrma/1d1c/cmd/entgo/ent/schema"
)

const (
	// Label holds the string label denoting the group type in the database.
	Label = "group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"

	// Table holds the table name of the group in the database.
	Table = "groups"
)

// Columns holds all SQL columns are group fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	fields = schema.Group{}.Fields()

	// descName is the schema descriptor for name field.
	descName = fields[0].Descriptor()
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator = descName.Validators[0].(func(string) error)
)
